name: web-client
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  web-client:
    uses: digital-stage/d2cloud/.github/workflows/_stages.yml@main
    with:
      component: web-client